CREATE TABLE IF NOT EXISTS users (
    user_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_name TEXT NOT NULL,
    password TEXT NOT NULL,
    display_name TEXT NOT NULL,
    phone TEXT NOT NULL UNIQUE,
    tenant TEXT NOT NULL,
    status TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tenants (
    tenant_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    tenant_name TEXT NOT NULL,
    host_name TEXT NOT NULL,
    port TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

