# Resolve react_native_pods.rb with node to allow for hoisting
require_relative('../node_modules/react-native/scripts/react_native_pods')
require_relative('../node_modules/react-native-permissions/scripts/setup')

# use_modular_headers!
platform :ios, min_ios_version_supported
prepare_react_native_project!

# config for react-native-permissions
setup_permissions([
  "Camera",
  "LocationAlways",
  "LocationWhenInUse",
  "Microphone",
  "Notifications",
  "PhotoLibrary",
  "PhotoLibraryAddOnly"
])

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'BrekekePhone' do
  config = use_native_modules!
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    :new_arch_enabled => false,
    :hermes_enabled => false,
    :fabric_enabled => false,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'React-jsc', :path => '../node_modules/react-native/ReactCommon/jsc', :modular_headers => true
  pod 'react-native-document-picker', :path => '../node_modules/@react-native-documents/picker', :modular_headers => true
  pod 'react-native-video', :path => '../node_modules/react-native-video', :modular_headers => true

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    installer.pods_project.targets.each do |target|
      if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
        target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
        
        # Cho phép non-modular includes trong Frameworks để bỏ qua lỗi
        config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'

        # Hạ chuẩn C++ của thư viện fmt xuống c++17 để fix lỗi "consteval function is not a constant expression" với Xcode mới
        if target.name == 'fmt'
          config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
        end

        # Ép trình biên dịch không coi lỗi "non-modular-include" thành ERROR
        cflags = config.build_settings['OTHER_CFLAGS'] || ['$(inherited)']
        cflags = Array(cflags) unless cflags.is_a?(Array)
        cflags << '-Wno-error=non-modular-include-in-framework-module'
        config.build_settings['OTHER_CFLAGS'] = cflags.uniq

        cxxflags = config.build_settings['OTHER_CPLUSPLUSFLAGS'] || ['$(inherited)']
        cxxflags = Array(cxxflags) unless cxxflags.is_a?(Array)
        cxxflags << '-Wno-error=non-modular-include-in-framework-module'
        config.build_settings['OTHER_CPLUSPLUSFLAGS'] = cxxflags.uniq
      end
    end
  end
end
